name: Build and Release Towhee Operators

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Operators
      run: python generate_ops.py

    - name: copy real files
      run: |
        mkdir -p towhee_ops/.towhee
        rsync -aL ~/.towhee/ towhee_ops/.towhee/
        cp requirements.txt towhee_ops/
        
    - name: create tar.gz without symlinks
      run: |
        tar czvf towhee_ops.tar.gz towhee_ops
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'v1.0.2'
        name: 'Towhee Operators v1.0.2'
        files: towhee_ops.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
